### ISSUE TITLE
EDRP doesn't seem to work when used in combination with min-ed-launcher

### ISSUE THREAD

**Issue by Razwerkz** [Lasa2/ED-RichPresence#33]
It seems that EDRP has some trouble when [rfvgyhn's Minimal ED Launcher](https://github.com/rfvgyhn/min-ed-launcher) is also being used.  For some reason, it can only properly display rich presence after EDRP has been launched *after* Elite has launched.

To reproduce, have Steam configured to launch Elite via min-ed-launcher.  I used the following arguments:
`cmd /c "MinEdLauncher.exe %command% /autorun /autoquit /edo"`
Set up EDRP to launch the game automatically.  Using the Steam protocol, targeting Steam and adding game args, and direct-linking min-ed-launcher are all viable options.  I used this as my target details:
`C:\Program Files (x86)\Steam\Steam.exe` `-gameidlaunch 359320 /edo`
Exit EDRP, then run it again.  When EDRP launches, it will launch min-ed-launcher, which will handle the game launch process.  As you load into the main menu, and then the game session itself, observe your Discord client for changes.

**Comment by VeeLume** [comment]
Fixed with the [latest release](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/releases/tag/V5.1)

**Comment by Razwerkz** [comment]
Hmm.  I'm still having issues.  I've tried every which way to launch EDRP (EDRP launches custom launcher via Steam, EDRP calls Steam to launch the custom launcher, EDRP launches the custom launcher directly, EDRP launched standalone before/after Elite)...  Now, it seems that EDRP can't hook into the game properly for me at all.

Furthermore, I got [this hang-up on application exit](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/files/11305109/edrp-2023-04-23_18-24-30_127670.log).  The application could not be fully closed, and was then killed using Process Explorer.

**Comment by VeeLume** [comment]
I fixed the crash, which was a simple oversite, with the [latest release](https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/releases/tag/V5.2)

**Comment by Razwerkz** [comment]
Nice, the app works for me again.

I can get rich presence if EDRP handles autostart.  However, I *can't* get the same effect by having min-ed-launcher launch EDRP (with autostart disabled, as the launcher handles that) instead.  I'm not sure if this is a limitation on EDRP's end or on the custom launcher's.

**Comment by VeeLume** [comment]
That seems to be an issue with the min-ed-launcher. For some reason it freezes the whole app until you press CTRL-C, so my guess its caused by the way the launcher starts the processes.

**Comment by Razwerkz** [comment]
Ah.  That's probably not something that can be changed without setting explicit rules within min-ed-launcher for that specific app.  I can still launch Elite and all my other apps using the "EDRP calls Steam calls min-ed-launcher" method, so I'm plenty satisfied with having EDRP as my Elite shortcut.

**Comment by Razwerkz** [comment]
Turns out the issue was caused by having Desktop Game Theatre active.
https://github.com/rfvgyhn/min-ed-launcher/issues/91
Issue is resolved.
